[workspace]
resolver = "2"
members = [
    "crates/bpg-bitstream",
    "crates/bpg-image",
    "crates/bpg-format",
    "crates/bpg-hevc",
    "crates/bpg-hevc-decode",
    "crates/bpg-decode",
    "crates/bpg-encode",
    "crates/still265",
    "crates/bpg-tools",
    "crates/toojpeg",
]

[workspace.package]
version = "0.5.2"
edition = "2021"
license = "GPL3"

[profile.release]
debug = "line-tables-only"
codegen-units = 1
lto = "thin"
strip = false

[profile.profiling]
inherits = "release"
debug = true
lto = false
strip = false
codegen-units = 16

[profile.release-lto]
inherits = "release"
lto = "fat"
codegen-units = 1
debug = "line-tables-only"
strip = false
