[workspace]
resolver = "2"
members = [
    "crates/bpg-bitstream",
    "crates/bpg-image",
    "crates/bpg-format",
    "crates/bpg-hevc",
    "crates/bpg-hevc-decode",
    "crates/bpg-decode",
    "crates/bpg-encode",
    "crates/bpg-x265-sys",
    "crates/bpg-x265",
    "crates/bpg-tools",
]

[workspace.package]
version = "0.1.0"
edition = "2021"
license = "MIT"

[profile.release]
debug = true
