//! Raw FFI bindings to the vendored x265 (release 4.1, `X265_BUILD=215`),
//! generated by `bindgen` in `build.rs`. See `bpg-x265` for the safe wrapper.
//!
//! Use [`x265_api_query`] with [`X265_BUILD`] to obtain the `x265_api`
//! function table for a given bit depth — this avoids depending on the
//! build-number-versioned `x265_api_get_215` symbol (which is what the
//! `x265_api_get` macro expands to in C).

#![allow(non_upper_case_globals)]
#![allow(non_camel_case_types)]
#![allow(non_snake_case)]
#![allow(dead_code)]

include!(concat!(env!("OUT_DIR"), "/bindings.rs"));
